<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250316072342 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE builder_data_source (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, selected_columns JSON DEFAULT NULL, data_source_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_641A1F611A935C57 ON builder_data_source (data_source_id)');
        $this->addSql('CREATE TABLE visualization_builder_progress (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(255) NOT NULL, data_source_id INT DEFAULT NULL, last_modified_by_id INT NOT NULL, visualization_configuration_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_BD3224331A935C57 ON visualization_builder_progress (data_source_id)');
        $this->addSql('CREATE INDEX IDX_BD322433F703974A ON visualization_builder_progress (last_modified_by_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BD322433D210691 ON visualization_builder_progress (visualization_configuration_id)');
        $this->addSql('ALTER TABLE builder_data_source ADD CONSTRAINT FK_641A1F611A935C57 FOREIGN KEY (data_source_id) REFERENCES data_source (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE visualization_builder_progress ADD CONSTRAINT FK_BD3224331A935C57 FOREIGN KEY (data_source_id) REFERENCES data_source (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE visualization_builder_progress ADD CONSTRAINT FK_BD322433F703974A FOREIGN KEY (last_modified_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE visualization_builder_progress ADD CONSTRAINT FK_BD322433D210691 FOREIGN KEY (visualization_configuration_id) REFERENCES visualization_configuration (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE wizard_data_source DROP CONSTRAINT fk_5249e8571a935c57');
        $this->addSql('DROP TABLE wizard_data_source');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE wizard_data_source (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, selected_columns JSON DEFAULT NULL, data_source_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_5249e8571a935c57 ON wizard_data_source (data_source_id)');
        $this->addSql('ALTER TABLE wizard_data_source ADD CONSTRAINT fk_5249e8571a935c57 FOREIGN KEY (data_source_id) REFERENCES data_source (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE builder_data_source DROP CONSTRAINT FK_641A1F611A935C57');
        $this->addSql('ALTER TABLE visualization_builder_progress DROP CONSTRAINT FK_BD3224331A935C57');
        $this->addSql('ALTER TABLE visualization_builder_progress DROP CONSTRAINT FK_BD322433F703974A');
        $this->addSql('ALTER TABLE visualization_builder_progress DROP CONSTRAINT FK_BD322433D210691');
        $this->addSql('DROP TABLE builder_data_source');
        $this->addSql('DROP TABLE visualization_builder_progress');
    }
}
