<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250317022057 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE table_configuration (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, selected_columns JSON DEFAULT NULL, sorting JSON DEFAULT NULL, filters JSON DEFAULT NULL, visualization_configuration_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D03DE5DAD210691 ON table_configuration (visualization_configuration_id)');
        $this->addSql('ALTER TABLE table_configuration ADD CONSTRAINT FK_D03DE5DAD210691 FOREIGN KEY (visualization_configuration_id) REFERENCES visualization_configuration (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE table_configuration DROP CONSTRAINT FK_D03DE5DAD210691');
        $this->addSql('DROP TABLE table_configuration');
    }
}
