<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250316064425 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE builder_data_source (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, selected_columns JSON DEFAULT NULL, data_source_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5249E8571A935C57 ON builder_data_source (data_source_id)');
        $this->addSql('ALTER TABLE builder_data_source ADD CONSTRAINT FK_5249E8571A935C57 FOREIGN KEY (data_source_id) REFERENCES data_source (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE builder_data_source DROP CONSTRAINT FK_5249E8571A935C57');
        $this->addSql('DROP TABLE builder_data_source');
    }
}
